/**
 * Qa mobile api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: mb
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/* tslint:disable:no-unused-variable member-ordering max-line-length interface-name */

import * as models from './models';

export interface SingleValueNode {
    typeReference?: models.IEdmTypeReference;
    kind?: SingleValueNode.KindEnum;
}
export namespace SingleValueNode {
'use strict';

    export enum KindEnum {
        None = 'None' as any,
        Constant = 'Constant' as any,
        Convert = 'Convert' as any,
        NonentityRangeVariableReference = 'NonentityRangeVariableReference' as any,
        BinaryOperator = 'BinaryOperator' as any,
        UnaryOperator = 'UnaryOperator' as any,
        SingleValuePropertyAccess = 'SingleValuePropertyAccess' as any,
        CollectionPropertyAccess = 'CollectionPropertyAccess' as any,
        SingleValueFunctionCall = 'SingleValueFunctionCall' as any,
        Any = 'Any' as any,
        CollectionNavigationNode = 'CollectionNavigationNode' as any,
        SingleNavigationNode = 'SingleNavigationNode' as any,
        SingleValueOpenPropertyAccess = 'SingleValueOpenPropertyAccess' as any,
        SingleEntityCast = 'SingleEntityCast' as any,
        All = 'All' as any,
        EntityCollectionCast = 'EntityCollectionCast' as any,
        EntityRangeVariableReference = 'EntityRangeVariableReference' as any,
        SingleEntityFunctionCall = 'SingleEntityFunctionCall' as any,
        CollectionFunctionCall = 'CollectionFunctionCall' as any,
        EntityCollectionFunctionCall = 'EntityCollectionFunctionCall' as any,
        NamedFunctionParameter = 'NamedFunctionParameter' as any
    }
}
